### ISSUE TITLE
不能使用，提示错误undefined symbol: g_log_context

### ISSUE THREAD

**Issue by Shawn106** [cosysun/FastDFSClient_Python#1]
您好。
按照你的提示进行了编译，将得到的FDFSPythonClient.so拷贝进了python的模块目录。
执行test.py时候提示错误undefined symbol: g_log_context。
不知道哪里出了问题？请问有解决的办法吗？本人比较小白，没学过C++。
Ubunt 14
FastDFS是最新的5.05版本。
root@ubunt:/home/doc/FastDFS/client/ClientForPython/test# python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import FDFSPythonClient
ImportError: /usr/lib/python2.7/dist-packages/FDFSPythonClient.so: undefined symbol: g_log_context

**Comment by Shawn106** [comment]
因为本人安装的时候目录和你的目录不同，因此对makefile做了一些修改。
一并帖出来：
INC_PATH = -I. -I../../tracker -I../../storage -I../ -I ../../common -I/usr/local/include -I/usr/lib/python2.7 -I/usr/include/python2.7 -I/usr/include/fastcommon -I/usr/include/fdfsdfst

**Comment by cosysun** [comment]
g_log_context 这个是fdfs客户端函数，请查看一下 是否建立了tracker 和 storaged 目录 这两个目录是来存储日志和数据的，如果不存在 g_log_context 可能会报错

**Comment by Shawn106** [comment]
请问是哪里是否建立tracker 和 storaged 目录 呢？
我把FastDFS 放置在/home/doc里了。
我只找到了/home/doc/FastDFS/storage 和/home/doc/FastDFS/tracker/
其他并没有发现建立tracker 和 storaged 目录 ？
该怎么办呢？

**Comment by Shawn106** [comment]
我需要把/home/doc/FastDFS/storage 和/home/doc/FastDFS/tracker 拷贝到哪里吗？

**Comment by Shawn106** [comment]
另外make的时候出现这种提示：
是否有影响呢？
root@ubunt:/home/doc/FastDFS/client/ClientForPython# make
g++ -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -shared -L/usr/lib -L../ -lfastcommon  -lfdfsclient  -lpthread -ldl -rdynamic -ljsonlib -o FDFSPythonClient.so FDFSPythonClient.o FDFSClient.o
root@ubunt:/home/doc/FastDFS/client/ClientForPython# make
g++ -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -c -fPIC FDFSPythonClient.cpp -I. -I/home/doc/FastDFS/tracker -I/home/doc/FastDFS/storage -I../ -I/home/doc/FastDFS/common -I/usr/include -I/usr/lib/python2.7 -I/usr/include/python2.7 -I/usr/include/fastcommon -I/usr/include/fdfsdfst -L/usr/lib -L../ -lfastcommon  -lfdfsclient  -lpthread -ldl -rdynamic -ljsonlib
g++ -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -c -fPIC FDFSClient.cpp -I. -I/home/doc/FastDFS/tracker -I/home/doc/FastDFS/storage -I../ -I/home/doc/FastDFS/common -I/usr/include -I/usr/lib/python2.7 -I/usr/include/python2.7 -I/usr/include/fastcommon -I/usr/include/fdfsdfst -L/usr/lib -L../ -lfastcommon  -lfdfsclient  -lpthread -ldl -rdynamic -ljsonlib
FDFSClient.cpp: In constructor ‘CFDFSClient::CFDFSClient()’:
FDFSClient.cpp:10:23: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
  m_RecvBufferInfo = {0};
                       ^
FDFSClient.cpp:10:19: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
  m_RecvBufferInfo = {0};
                   ^
g++ -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -shared -L/usr/lib -L../ -lfastcommon  -lfdfsclient  -lpthread -ldl -rdynamic -ljsonlib -o FDFSPythonClient.so FDFSPythonClient.o FDFSClient.o

**Comment by cosysun** [comment]
没有影响

**Comment by Shawn106** [comment]
那是否是fastdfs版本的问题呢？
请问你使用的是哪个版本？
我装一下进行测试，看是否是版本问题。

**Comment by cosysun** [comment]
跟版本没关系，我也是用5.05 这是因为 fastdfs的目录没找到，而且注意权限问题，是否可以写入

**Comment by cosysun** [comment]
你在配置文件中配置的目录 下 要新建一个tracker目录

**Comment by cosysun** [comment]
还有一个就是注意你的lib是否都链接完整，从而导致找不到这个变量

**Comment by Shawn106** [comment]
重新换了一个环境安装了一次
debian 7 Wheezy,
make的时候竟然提示json库不匹配：
我另外可以从哪里得到能匹配的json库呢？
root@debian:~/FastDFS/client/ClientForPython# make
g++ -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -shared -L/usr/local/lib -L/usr/lib/i386-linux-gnu -L../ -lfastcommon  -lfdfsclient  -lpthread -ldl -rdynamic -ljsonlib -o FDFSPythonClient.so FDFSPythonClient.o FDFSClient.o
/usr/bin/ld: skipping incompatible /usr/local/lib/libjsonlib.so when searching for -ljsonlib
/usr/bin/ld: skipping incompatible /usr/local/lib/libjsonlib.a when searching for -ljsonlib
/usr/bin/ld: skipping incompatible /usr/local/lib/libjsonlib.so when searching for -ljsonlib
/usr/bin/ld: skipping incompatible /usr/local/lib/libjsonlib.a when searching for -ljsonlib
/usr/bin/ld: cannot find -ljsonlib
collect2: error: ld returned 1 exit status
make: **\* [FDFSPythonClient.so] Error 1

**Comment by Shawn106** [comment]
是否因为32位的原因？
root@debian:~/FastDFS/client/ClientForPython# uname   -a
Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.63-2+deb7u1 i686 GNU/Linux

**Comment by cosysun** [comment]
你这个是json库连接没找到，需要将其路径添加到PATH里。。。另外跟32bit没关系，你注意看一下 tracker 和 storage下有没有错误日志。。

**Comment by Shawn106** [comment]
我重新测试了，如果把json两个文件libjsonlib.so，libjsonlib.a删除会提示其他错误，证明json库是可以找到的。
root@debian:~/FastDFS/client/ClientForPython# file /usr/local/lib/libjsonlib.so
/usr/local/lib/libjsonlib.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x7f1c1b6f6f8a08512e9a446232628d1931f82de7, not stripped

由此看来这个文件是64位的，估计很有可能是这种原因。
网上也查到有类似的情况：
http://blog.csdn.net/kissnsms/article/details/16116359
能否提供一下32位的文件或者下载地址？
小白google搜了半天一无所获，没找到下载的地方，不知道该怎么整了。。。

**Comment by cosysun** [comment]
https://github.com/open-source-parsers/jsoncpp  这个是源代码 可以下下来编译一下

**Comment by Shawn106** [comment]
实在太小白了，
整了半天也没整出来你那几个东西。。。 :( 
大神能指点指点吗？写个小小的步骤也行。
:+1:

**Comment by cosysun** [comment]
你用fastdfs的C++客户端 能测试的通吗。。如果能测试的通的话，这个也应该没问题的，首先检查是否正确安装了 fastdfs，然后用fastdfs的客户端测试整个分布式系统是否正确。。。

**Comment by Shawn106** [comment]
fastdfs自带的客户端测试完全没问题。
系统也正常使用。
jsoncpp终于编译成功了。
方法：http://www.cnblogs.com/kingcat/archive/2012/06/14/2549050.html
查看了依赖库应该完全没问题了啊。
root@debian:~/FastDFS/client/ClientForPython# ldd FDFSPythonClient.so
    linux-gate.so.1 =>  (0xb77ae000)
    libfastcommon.so => /usr/local/lib/libfastcommon.so (0xb776d000)
    libfdfsclient.so => /usr/local/lib/libfdfsclient.so (0xb7754000)
    libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb773a000)
    libdl.so.2 => /lib/i386-linux-gnu/i686/cmov/libdl.so.2 (0xb7736000)
    libjsonlib.so => /usr/local/lib/libjsonlib.so (0xb76d3000)
    libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb75e7000)
    libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xb75c1000)
    libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb75a3000)
    libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb743e000)
    /lib/ld-linux.so.2 (0xb77af000)
但是测试的时候就出问题了。。。。
root@debian:~/FastDFS/client/ClientForPython# cp -a FDFSPythonClient.so  /usr/lib/python2.7/dist-packages
root@debian:~/FastDFS/client/ClientForPython# python test/test.py
Traceback (most recent call last):
  File "test/test.py", line 5, in <module>
    import FDFSPythonClient
ImportError: /usr/lib/python2.7/dist-packages/FDFSPythonClient.so: undefined symbol: _ZN4Json5ValueaSERKS0_

导入模块还是出错，难道是编译的jsoncpp版本不对？

**Comment by Shawn106** [comment]
另外，日志一切正常
tacker日志部分：
[2015-02-13 15:14:48] INFO - FastDFS v5.05, base_path=/home/fastdfs/tracker, run_by_group=, run_by_user=, connect_timeout=30s, network_timeout=60s, port=22122, bind_addr=10.211.55.3, max_connections=256, accept_threads=1, work_threads=4, store_lookup=2, store_group=, store_server=0, store_path=0, reserved_storage_space=10.00%, download_server=0, allow_ip_count=-1, sync_log_buff_interval=10s, check_active_interval=120s, thread_stack_size=64 KB, storage_ip_changed_auto_adjust=1, storage_sync_file_max_delay=86400s, storage_sync_file_max_time=300s, use_trunk_file=0, slot_min_size=256, slot_max_size=16 MB, trunk_file_size=64 MB, trunk_create_file_advance=0, trunk_create_file_time_base=02:00, trunk_create_file_interval=86400, trunk_create_file_space_threshold=20 GB, trunk_init_check_occupying=0, trunk_init_reload_from_binlog=0, trunk_compress_binlog_min_interval=0, use_storage_id=0, id_type_in_filename=ip, storage_id_count=0, rotate_error_log=0, error_log_rotate_time=00:00, rotate_error_log_size=0, log_file_keep_days=0, store_slave_file_use_link=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s
[2015-02-13 15:14:48] INFO - local_host_ip_count: 2,  127.0.0.1  10.211.55.3
[2015-02-13 15:14:55] INFO - file: tracker_relationship.c, line: 383, selecting leader...
[2015-02-13 15:14:55] INFO - file: tracker_relationship.c, line: 401, I am the new tracker leader 10.211.55.3:22122

下面是storage日志
[2015-02-13 15:14:55] INFO - FastDFS v5.05, base_path=/home/fastdfs/storage, store_path_count=1, subdir_count_per_path=256, group_name=g1, run_by_group=, run_by_user=, connect_timeout=30s, network_timeout=60s, port=23000, bind_addr=10.211.55.3, client_bind=1, max_connections=256, accept_threads=1, work_threads=4, disk_rw_separated=1, disk_reader_threads=1, disk_writer_threads=1, buff_size=256KB, heart_beat_interval=30s, stat_report_interval=60s, tracker_server_count=1, sync_wait_msec=50ms, sync_interval=0ms, sync_start_time=00:00, sync_end_time=23:59, write_mark_file_freq=500, allow_ip_count=-1, file_distribute_path_mode=0, file_distribute_rotate_count=100, fsync_after_written_bytes=0, sync_log_buff_interval=10s, sync_binlog_buff_interval=10s, sync_stat_file_interval=300s, thread_stack_size=512 KB, upload_priority=10, if_alias_prefix=, check_file_duplicate=0, file_signature_method=hash, FDHT group count=0, FDHT server count=0, FDHT key_namespace=, FDHT keep_alive=0, HTTP server port=8888, domain name=, use_access_log=0, rotate_access_log=0, access_log_rotate_time=00:00, rotate_error_log=0, error_log_rotate_time=00:00, rotate_access_log_size=0, rotate_error_log_size=0, log_file_keep_days=0, file_sync_skip_invalid_record=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s
[2015-02-13 15:14:55] INFO - file: storage_param_getter.c, line: 191, use_storage_id=0, id_type_in_filename=ip, storage_ip_changed_auto_adjust=1, store_path=0, reserved_storage_space=10.00%, use_trunk_file=0, slot_min_size=256, slot_max_size=16 MB, trunk_file_size=64 MB, trunk_create_file_advance=0, trunk_create_file_time_base=02:00, trunk_create_file_interval=86400, trunk_create_file_space_threshold=20 GB, trunk_init_check_occupying=0, trunk_init_reload_from_binlog=0, trunk_compress_binlog_min_interval=0, store_slave_file_use_link=0
[2015-02-13 15:14:55] INFO - file: storage_func.c, line: 254, tracker_client_ip: 10.211.55.3, my_server_id_str: 10.211.55.3, g_server_id_in_filename: 53990154
[2015-02-13 15:14:55] INFO - local_host_ip_count: 2,  127.0.0.1  10.211.55.3
[2015-02-13 15:14:55] INFO - file: tracker_client_thread.c, line: 310, successfully connect to tracker server 10.211.55.3:22122, as a tracker client, my ip is 10.211.55.3
[2015-02-13 15:15:26] INFO - file: tracker_client_thread.c, line: 1235, tracker server 10.211.55.3:22122, set tracker leader: 10.211.55.3:22122

测试上传的记录：
root@debian:~/FastDFS/client/ClientForPython# fdfs_test /etc/fdfs/client.conf upload /etc/fdfs/client.conf
This is FastDFS client test program v5.05

Copyright (C) 2008, Happy Fish / YuQing

FastDFS may be copied only under the terms of the GNU General
Public License V3, which may be found in the FastDFS source kit.
Please visit the FastDFS Home Page http://www.csource.org/ 
for more detail.

[2015-02-13 15:15:37] DEBUG - base_path=/home/fastdfs, connect_timeout=30, network_timeout=60, tracker_server_count=1, anti_steal_token=0, anti_steal_secret_key length=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s, use_storage_id=0, storage server id count: 0

tracker_query_storage_store_list_without_group: 
    server 1. group_name=, ip_addr=10.211.55.3, port=23000

group_name=g1, ip_addr=10.211.55.3, port=23000
storage_upload_by_filename
group_name=g1, remote_filename=M00/00/00/CtM3A1TdpJmABPGmAAAFrAcwo8I03.conf
source ip address: 10.211.55.3
file timestamp=2015-02-13 15:15:37
file size=1452
file crc32=120628162
example file url: http://10.211.55.3/g1/M00/00/00/CtM3A1TdpJmABPGmAAAFrAcwo8I03.conf
storage_upload_slave_by_filename
group_name=g1, remote_filename=M00/00/00/CtM3A1TdpJmABPGmAAAFrAcwo8I03_big.conf
source ip address: 10.211.55.3
file timestamp=2015-02-13 15:15:37
file size=1452
file crc32=120628162
example file url: http://10.211.55.3/g1/M00/00/00/CtM3A1TdpJmABPGmAAAFrAcwo8I03_big.conf

**Comment by cosysun** [comment]
你测试一下 test_upload.py 这个看看

**Comment by cosysun** [comment]
在test目录下 导入一张 图片 命名为1.png

**Comment by Shawn106** [comment]
:100: 
喜大普奔！
终于成功了! :+1:
非常感谢!!! :+1:虽然还没有对这个模块进行研究，不过刚刚测试成功了。
果真是因为jsoncpp的版本问题，我编译的版本和你的版本不一致，需要将json/目录下所有的文件更新为自己编译版本的。
换句话说，就是需要自行编译jsoncpp，jsoncpp相关的文件都替换为自己的。
下面是日志。貌似test_upload.py里面的import写错了。
应该为：import FDFSPythonClient 少了个字母t

root@debian:~/FastDFS/client/ClientForPython# python test/test_upload.py
[2015-02-13 15:30:28] DEBUG - base_path=/home/fastdfs, connect_timeout=30, network_timeout=60, tracker_server_count=1, anti_steal_token=0, anti_steal_secret_key length=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s, use_storage_id=0, storage server id count: 0

0.503063201904
(0, 'g1/M00/00/00/CtM3A1TdqBSAeHA-AAAFrAcwo8I8448731')

虽然ubunt环境下尚未成功。但是虚拟机debian成功了，希望就很大啦。
不知道我上面说的对不对？
希望对后来者有帮助。

**Comment by cosysun** [comment]
给你点赞，是我考虑不周，非常谢谢你的努力。。希望这个客户端对你有用！！如果发现新问题，欢迎你提交版本
